# Generated by Django 3.0 on 2019-12-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tag',
        ),
    ]
