# Generated by Django 3.0.1 on 2019-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191225_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='vote',
            new_name='badVote',
        ),
        migrations.AddField(
            model_name='board',
            name='goodVote',
            field=models.IntegerField(default=0),
        ),
    ]
