# Generated by Django 3.0 on 2019-12-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.CharField(max_length=1000),
        ),
    ]
